### ISSUE TITLE
为何导入项目时header项目会找不到RecycleView呢，好奇怪，明明导入了，别的项目没这问题

### ISSUE THREAD

**Issue by envyfan** [CrazyTaro/RecycleViewAdapter#1]

**Comment by CrazyTaro** [comment]
你好,项目本身是有依赖于RecycleView的;刚才也尝试了全新的项目在原本没有依赖RecycleView的情况下使用RecycleView,是可以正常查找到并使用的.
建议你尝试clean一下project或者rebuild一下,有时可能是AS的链接问题或者是没有正确地索引到.如果实在不行考虑一下能不能重新导入一次或者在项目加直接添加RecycleView的依赖看能否解决这个问题.
希望可以帮到你~感谢支持~~谢谢!

**Comment by envyfan** [comment]
不可能跑起来吧，我找到原因了：recycle_header_adapter/header/src/main/java/com/taro/headerrecycle/helper/RecycleVIewScrollHelper.java  这个文件的名和类名不一样 类名是RecycleViewXXXXX 文件名却是 RecycleVIewXXXX 改过来就不会找不到引入的RecycleView了，可是跑起来的时候又说找不到ct_debug.jks 。= -怎么弄呢。

**Comment by envyfan** [comment]
Error:Execution failed for task ':app:validateDebugSigning'.

> Keystore file C:\Users\ISSUSER\Desktop\Demo\recycle_header_adapter-master\app\Users\taro\Desktop\ct_debug.jks not found for signing config 'debug'.

**Comment by CrazyTaro** [comment]
关于类名的问题...这是因为之前写的时候可以手抖了,所以大写了一个字母...上次更新项目就已经修正了.并且之后可能会对项目添加一点额外的功能修改(不会影响原来代码的功能和使用方式的.)
看样子你是用module引的吧,因为项目新修改后并没有上传到maven,建议你使用gradle直接引用.
关于你的签名问题,能解决就好了,不过一般签名应该是本地的问题,跟引用的库一般不会有冲突的.
非常感谢支持,修改代码造成的麻烦真不好意思,下次会更加小心的,谢谢~

**Comment by envyfan** [comment]
我是gradle小白。。刚刚把debug那栏的去掉，项目就能跑起来了。~！。先去研究下先。不懂我再ISSUES
