### ISSUE TITLE
启动scrollActivity报错

### ISSUE THREAD

**Issue by envyfan** [CrazyTaro/RecycleViewAdapter#2]
注释了activity_scroll里的FloatingActionButton 这个View后就能正常使用

**Comment by envyfan** [comment]
测试机是 红米note3

**Comment by CrazyTaro** [comment]
我看不到你的项目,所以我不能确定你是什么问题造成的啊.
如果不是因为库的问题我很难帮你确定问题原因或者是有没有具体的异常log.
库的话之前是已经做过多个场合的测试,也测试过多种情况.当然不可能把所有机型都测试过,但都是没有问题的.你考虑一下是否有可能是其它的UI或者其它的问题导致的异常.
项目报错是很常见的,但出错的原因有任何可能.建议你再查查log,我没有你的项目也没有代码,你告诉我哪里错了我也没办法帮你分析出原因.
很抱歉无法帮上忙~

**Comment by envyfan** [comment]
没事，隐藏掉那View不影响 调试demo
