### ISSUE TITLE
如何在不滑动的情况下检查 recycleview是否item填充全屏？

### ISSUE THREAD

**Issue by envyfan** [CrazyTaro/RecycleViewAdapter#3]
目前作者的DEMO是在滑动的时候 逻辑判断（最后一个Item与recycleview之间的高度对比） item是否填充全屏，
那么如果我想初始化完数据之后 就判断 item有没有填充满全屏（不滑动） 那应该怎么弄呢。

**Comment by CrazyTaro** [comment]
如果你指的是在RecycleView已经显示出item时,不通过滑动确定是否当前的item已经全部显示在RecycleView中的话.你可以尝试这么做.

```
//获取RecycleView当前显示的view的数量
int viewCount=mRv.getChildCount();
//获取adapter中item的总数量
int itemCount=mAdapter.getCount;
//当显示的view数量达到item的数量时,说明已经全部显示了
return viewCount>=itemCount;
```

以上建议做个测试.因为childCount是RecycleView的子view数量,不确定会不会包含了缓存的一小部分view的数量.(这里说一小部分是因为之前尝试过在某些情况下,RecycleView已经将某个view滑动出界面后,通过getChild(0)获取的view依然是已经被滑出界面而不在RecycleView中显示的view).
存在这种可能性getChildCount()获取的数量并不完全准确,但在精确度要求不高的情况下,应该可以满足你的需求了.

**Comment by envyfan** [comment]
怎么知道RecycleView已经显示出所有item 没？ 有没有具体的回调？ 我试了下recycleView的好几个监听，感觉都不太像。。。

**Comment by CrazyTaro** [comment]
RecycleView本身的item是动态的,是复用的,不存在显示出所有item的情况.所有的view都是在需要使用的时候被复用了.所以要不就你是滑动到底部没有其它数据了,那么就是**显示过**所有的item,但此时不代表所有的item都显示在界面上被看到.

如果你要查看是不是所有的item都被显示在界面上看到,可以尝试一下我上面说的.RecycleView每一个item数据加载一个view,当加载并显示的view的数量跟adapter中的item的数量一样多时(或者更多时),说明RecycleView已经显示在界面上的view是展示了adapter中的所有数据了.

例如:adapter的数据量只有3(即getCount()),而RecycleView足够高的情况下可以显示4个item,那么此时`rv.getChildCount()`的值应该就是3了(可以达到4,但是adapter最多只有3个数据,所以也只会显示3个).
只有当`rv.getChildCount()`的值大于4个时(一屏最多可以显示的view数量),才说明adapter中的数据有可能超过4,即还有其它的数据没有显示在界面上,否则应该全部显示在RecycleView中了.

不知道我这里说的是不是你想要的.按我的理解应该是你要确定当前RecycleView显示的是不是所有的item了.

**Comment by envyfan** [comment]
好的，谢谢作者，我大概明白你的意思。
