### ISSUE TITLE
demo下载下来运行不了

### ISSUE THREAD

**Issue by iurgnid** [CrazyTaro/RecycleViewAdapter#4]
Error:Execution failed for task ':app:validateSigningDebug'.
> Keystore file E:\ASWorkSpace\recycle_header_adapter-master\app\Users\taro\Desktop\ct_debug.jks not found for signing config 'debug'.
这个keystore错误，不知道怎么解决

**Comment by CrazyTaro** [comment]
这个是签名的问题,现在已经屏蔽掉了.根据新提交的内容屏蔽对应的代码或者是直接pull一下代码更新一下重新运行应该没有问题的.
这个可能是之前测试时加的签名, 实际上运行时不并不需要任何签名.不好意思~

**Comment by CrazyTaro** [comment]
请问问题解决了么?如果解决了我就把issue关掉咯

**Comment by iurgnid** [comment]
恩恩，谢谢了，解决了

**Comment by iurgnid** [comment]
有个需求是recyclerview 嵌套recyclerview，两个rv都是gridlayoutmanager，且是vertical的朝向，内部的rv能滑动，外面的rv也能滑动，大神，有没有思路给一个呢

**Comment by CrazyTaro** [comment]
这个有点复杂哦,听你说的意思我只是理解为类似9宫格中再拆分成9宫格这样子?
正常来说不太可能数量很多,如果数量不多的话我建议外层或者是内层考虑用其它的去解决而不是用recycleview.如 : 自定义view包裹recycleview或者是recycleView包裹自定义view. 
这种方式适用于类似微信朋友圈查看多图的形式.

如果说数量很多又不确定的话,recycleView也不是不行吧,本身他支持nescroll的,所以你如果子view也使用recycleview的话应该是可以拦截到父控件的滑动事件.不过肯定是同一时间只能有一个view在滑动.相互嵌套的话recycleView是没有问题的,但是对于滑动控制来说目前还没有尝试过,所以我不能给出一个准确的答案.

不是特别清楚你具体的一个应用场景,建议思考一下有没有其它的解决方案,毕竟滑动控制的嵌套不是不能做,但是涉及到很复杂的控件时,要做好这个就不容易了.而且万一出问题后期你得有足够的时间来维护哦.

如果有点想法的话可以把具体的应用场景详细一下,我可以帮你想想解决方案.不过我也不算是大神,没有那么权威,就是相互帮助,难保有一天我也会遇到这样的问题.加油~

**Comment by iurgnid** [comment]
非常感谢，需求是倾向于recyclerview里面嵌套数量不确定的item，确实类似九宫格，都是垂直排列外面里面都能滚动。https://github.com/rubensousa/RecyclerViewSnap差不多这个效果，不过还没研究。是snap帮助类好像。

**Comment by CrazyTaro** [comment]
瞄了一下,这个自己做的话可能会花的时间有点久....如果你的内嵌item需要滑动,那内嵌的recycleView就要固定高度了;但是嵌套滑动需要自己处理,默认他没有处理.
如果你只是做一个九宫格类型不需要滑动的,我之前倒是写了一个控件可能会用得上.如果需要再联系我吧.这个issue我关了咯~有任何问题欢迎再提出来,谢谢~
